name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
      - name: Build
        run: |
          cd backend
          docker buildx build \
            --platform linux/arm64/v8 \
            -t docker.stefangeneralao.com/stilipshue-backend \
            --load .
      - name: Push
        run: docker push docker.stefangeneralao.com/stilipshue-backend

  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
      - name: Build
        run: |
          cd frontend
          docker buildx build \
            --platform linux/arm64/v8 \
            -t docker.stefangeneralao.com/stilipshue-frontend \
            --load .
      - name: Push
        run: docker push docker.stefangeneralao.com/stilipshue-frontend
